
    drop table answer if exists;

    drop table delete_status if exists;

    drop table question if exists;

    drop table user if exists;

	create table user (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255) not null,
        password varchar(255) not null,
        user_id varchar(20) not null,
        primary key (id)
    );
	 create table question (
        id bigint generated by default as identity,
        contents varchar(255) not null,
        delete_status integer,
        reg_date varchar(255) not null,
        title varchar(255) not null,
        writer_id bigint,
        primary key (id)
    );
    create table answer (
        id bigint generated by default as identity,
        contents varchar(255) not null,
        reg_date varchar(255),
        question_id bigint,
        writer_id bigint,
        primary key (id)
    );

    create table delete_status (
        id bigint generated by default as identity,
        reg_date varchar(255),
        question_id bigint,
        writer_id bigint,
        primary key (id)
    );


    alter table user 
        add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id);

    alter table answer 
        add constraint fk_question_to_answer 
        foreign key (question_id) 
        references question;

    alter table answer 
        add constraint fk_user_to_answer 
        foreign key (writer_id) 
        references user;

    alter table delete_status 
        add constraint fk_question_to_answer2
        foreign key (question_id) 
        references question;